# Generated by Django 5.2.1 on 2025-10-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('cloth_name', models.CharField(null=True)),
                ('fashion_name', models.CharField(null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
