# Generated by Django 5.2.1 on 2025-10-23 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_clothes_user_relation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='cloth_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='fashion_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='relation',
        ),
    ]
