# Generated by Django 5.2.1 on 2025-11-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('★★★★★', '★★★★★'), ('★★★★☆', '★★★★☆'), ('★★★☆☆', '★★★☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★☆☆☆☆', '★☆☆☆☆')], max_length=5)),
            ],
        ),
    ]
