# Generated by Django 5.2.1 on 2025-11-22 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='khan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clothes'),
        ),
    ]
