# Generated by Django 5.2.1 on 2025-11-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customerreview_khan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='info',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
