# Generated by Django 5.2.1 on 2025-11-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customerreview_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='rating',
        ),
    ]
