# Generated by Django 5.2.1 on 2025-11-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customerreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(null=True),
        ),
    ]
