# Generated by Django 5.2.1 on 2025-11-27 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.clothes'),
            preserve_default=False,
        ),
    ]
